apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: commit-status-tracker-git-secret
  namespace: cicd
spec:
  encryptedData:
    token: AgC1q51y4BinJh/CeoTbk47QD1TsgwU3Toe/p+xAzp+1xdL6ILX+SjuGLlnaS6w/t2Xe1KkUxgdowlxudtZRnw5yKM1ulRJ7Cq0XSV9GpPItCf2FuFLBWpwo2ysExekIXjMRA3vCwMyPQWEqWFmNWYKD2yxSNM10Jk2i6WSX81WkybKYXgiR38KUcqGNA4dY2/4h+ZJJSdLhJlhtD3Jw5mDQH1thGS/gD3THHljaKbng2BkYbgoBf2DuEZK0HBHlkp/RrVIsz3k25JThtVn/6/Fmp9YB9kMGU9JgogSXMDbMfqBDXu3U2fzg9jVMGmDVyk0odjX16gDb2vGHsHYfoxpiYVxb4w41sUL/5tghV8nSBxh6ozF6nh6HZZCCwBjqtge/u7/RAwblm6MbHCN6EDelkX78/SgnGBCtKzE2D7b+VfYuQdzfpzNMDGgpf0tdYicFKETA6Zc3HHpzKZbIeKiUBffpp41lLSz1XqB3nuqBJ0mieCpTPT+yH1cICWtmUZr/OebKk+h8hFiX13OBcuAhE+nq0m4346AgmBypGB3NPRkkWOCHB96tyZVbMt7y7dAFeN5gouY2kcbRdPa5ylBZGQqvrskOXGZF3f7ldcVrC+8iv13+fEmLYt8+ul4P7j3t/b6J/HfQPsrmI4KJ1swtx9WYwN3g3HiK7ppMGDMOBIHMuLVWYJusbrimhI0OUdXIrCxyTW9RECnqRHlaeqOPBdLCur241E+QAn9CacsCsiknWt9q8/3M
  template:
    metadata:
      creationTimestamp: null
      name: commit-status-tracker-git-secret
      namespace: cicd
    type: Opaque
status: {}
