apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: commit-status-tracker-git-secret
  namespace: cicd
spec:
  encryptedData:
    token: AgAfga1csfMLl/V36pM3eUOirBq1BcIfRD0QpLKC8bqJRIbbIHyvltKLMY6pwUPJi23ZDXq0czHikGblOSTPVRj0vwoR8QNFpbiC1XuFrYecaODgYuGcQwp9O2YLRynuxZNPj2oSTjZNuWd6JnDWIRfo17R1KvQdWil72n9Fhn8phyu8KMHBFpKj2RaPFnZCMER3gUkg79SeMfmPKMcuzCrdUTg7Rh0EDDXY1Wgk0J1qGFlPMbB/yw0Eb7Us7GiYB59u9N7BUuzcRnNPUU0hFUZfZcZDxFjydXKdNXie74hKyHAsc9to+w0rqxi+uOnEqlmrxVTp2bZtFquBQKufOGoI5L4AmGeyHcFMDdVIz2J17fVDycVK6LqWdHDWrfRnyp5wmIp+7KtfLvXQvACaj/LWYYURYGXdqdWsOrPQPXPgSQ7Pi/v5mvmfI7WvT9u0+pi+F5HVxY+Vt0fUujRIYC6fwYRDQH7BVpcRRuHcZWvnUEZOt5XtLtug9zCoNnuo2dXDlptlB9rshA18yTzysDLMuDjaERvDK/2pzeQTlHgCX28AJ92C4lJ8hPUfsj+w+QNnFMzLwh3e+6yZ00HKdyrG4y5ETxlZmL/FlsGkBx1QzOKROMTgOrlgFESsQHhdkGbLgskwZF0iqA225iMFvMTNnujiGgq7koFpaKK/bDAHQw1sdUnKfWshCFbMC3PB/wgT44pMrLsEGXPdNx2lHtEVcl5ABJdpJzflCsF70n5n4EtCKu5ETXHF
  template:
    metadata:
      creationTimestamp: null
      name: commit-status-tracker-git-secret
      namespace: cicd
    type: Opaque
status: {}
