apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgBrBjXuyRnMpXIP46XeHriLTc0P34C2tD6TxlGhbIY8teSqsUXpCEzBaFFAFzenHw1qMYfNuYivdlXnt03322IEuc+WrysmkseBM+R1mH7ztacpTGPtKwCAZnxxN+46xDO38m1QL7aVD8Qt1eQwbUicMWvhd8mjfW/AqOcPxgUYueryzha4oMqGeXR68PwjO2XbdbhksUuEERNbDEAo1C/STpKmSTaNe1i+r/Rurfp0jrQQ6bmQDriemSApT9AYCKrza48EZ0oRY3pxc5Qxgu96Q3d/1P1mXAwx4ADyTbVPpZiA6lp7CuazGl8SIE5VbLE2DHG1Feu1YnFEy427YCCPec21HxD6+pF65LPiYylewrKPbpmreOeplVf6bMFG8vOvommAcyHzQLxzaGy6oakZB3+3r8q0rbKhFEH5SPZTlGc3dsbDC4ASEvNshLjELcErr1e0+MzFI6Rmm8b12wdoSP+Yl7ABrsJwVXxHlY1pp4Q+QPPRlhwT3N9zM9hq7JnZ9wLEwoMaQRPscsJx3MFtYMoGqJYYK+ZTNvhsySvWA1vahoIuYKQ8CF/N3qzAwveRPzYwbhKqnrlCWlUGkoucmRIh1KYdoUI9eEgi5SirWwLFKkTPNMhE/P6MbDZyEuaGU17R78teGdAvI93ZaOuzvAknsztxeBMEkqjfxxN9T/eMbx/z5Ez0kxvxM8AfL7gKLNzvY1e/iWJ8E7z7vjAptqThnf1yAvcEnaLOXXXpC2eGU/qYwuRGIOG7I1v/OfPxcXDXG12pKTFVgSeY454j+UOgv3GNLVQOeyjbnehfiNmc1fpuuN+h/vV59dlp/p4LQRsQRVE85+IoOD+bsCF9qP+03HhGBN/T+6iYl/7hw2rjLxq1skUY6QmmnF+6No/Xzxk2NgaQyveHv5qRmrfE2RpvM12rgMQV9D04enfL23uTBFQLMWlmO0/uKcBT/w==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
