apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgCGUF1AocoOrDykQ0lo/mLLUQHKXLAv7Zf9cEhK/pK6cemMmM2D242k/oqG8fDaumAFoX5i+NY3rhyZYCKcterr6/l3lUHbciJer/3dIMM5XBBLrld51DNSAxXVmC8HUwib0yB+74P+xg7JQQd4EP09k+op9oYJgWjvFk4dFC4dI1G04fSpAdMsETPK81yikW77x9Fm8lyQIWs91mE7TnXt2tUlegAksoOs/u5vdZjevWaYGzLk3HkvRB7sHSAJCCb9VJyOgoMrNkWe8iIlmvWY0vKmzc7sUZCUkZEtbl7hhjgX5I+Md3N5wFEeUgonT5ZeCB9HyTSNOxq1oR6hvauWs3FErpdhAzKtl4YQOFX8n2YgDdQpqXkB+hDl08SgF40Ju1l29w3Vzy7L1XtfXerrZdSpPR2E+N2qMSMuRVWGV3Mdbj6DUQ7POwDzlg72thRCv/laYOx00yfxmLwv4TQnnRSCIWVqU2/sc0a5aELhuq/7wH4blEUNb06zbDrfO23UMoa/KwGfSv4V9M7dSZkXAbp5+oFzihPzDJ6V0X2kGbCzd3gdoiLekyMqFEwFH4rrDfoWpLZZM8t05vghfoByGsT46VeZpXIHuqEycfHtm6SnOm0P4FDYH5lWpCYBkB8XImDZT0/LbIqyjytwnToxB/99qvvpGzRQ3cwno2kyQWTJl1nobl1nFEpeentMD/QVUGfsOgONEtABOuWn6SZFZwuERAjBmeEV6aOKykRikociHTjYE/yjsyTbGfMb25LqiAM+9kinfKBuMElxuIpzhw8KYsn8e+7UBqjMSAHCk/7qQEbRruJ/WpGszoybwvh7SM4FXWeraIkPIbjHTC2FCXdd57MLZmt1+ziW0IPdcnF6f3VlHnw8vHstJ16DHWM4FfC90Z8F9T+qsc6b1RYnBWFUeTe739VgvkakgJKP+qGVMtcx+Q/6ScbJ8j0hTA==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
