apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgCpp95iod/GKO9FPuJ5P78Dp4/FKDR7sK1VYR5v5zDXN10BN155WTOmy1dJUxTe33J59sP0A2PotNJDXoXPntp0Tq8thl2DG4IAU7J9ZbWPozG0DXdszSrvSJ3OtFWpYfVKKu3u7vsW9TLo5j/xajTY7CfavSgrSy2oxQ+ciM3utWfGriT/eUK671x9DXYj84eOhXxWJLX10yql3bfhKy1lx9ZaCg3QJBjk3BRScHcbFb/+eARU/YrPfStCW9/HLicY2bxHU5LWJO+oEaCyd6pDFhenAZv0cc+BW2KaPvCIzGeyRIR+CFEPMnPHTeJmj2/xGaeLc3ju32+RXmnoxyEKbtlyyLVd0DxozYPHPTMU8ps9Tm/E5rcoL6gG26/0gj707VTxLzqudeofl+1f6STVTSgpLRmcIsZHFYvO5YFl06UDPIeJe2/YBFRP2W8G8Xj8hkVrEXd3vidiZVeDfs6hCBCmR8pptwijbK5zkNDuSQYGTcSA1a2sX3pYvrV9UXuz39Zy5WHGXiPTvGluxFH4SNY97WnUjIaqwNqigID6QchN0OceBvuytxu7sS8KZML+RMMcCBwy9HBvvaEK13b/i9ghnaMycZpqHd5ijP131JJKZFfJnTlcnpDsL6oPCrvgysMuERTk54OJL6dhKb018bS1/JR5cLbfVofb9Zu0Ahb0Ed3FWd7DIN0nhGkrotLc7dZu9ZpKnRYRFzOX6E2O+zaSjqO+HVnfd8T+7tiUNfGxYu+Dlm9n0L7ZSASJwYoLvV6hloxVeziZJWuvQLCeXb2k4wXkYXPCjyvGykBjAzohp4tpNK7JS1Ol8cSMFIj8uSehzByh2F+CZO+qbwyD3IehayqI9lRNGHef0qRx1mbPWY2k2VPoQ9plEnSn0RijXNtdF6fxXt8MAR4UBiNFaGEMvXXKHwynyfCGHXVyiCWw144ttYIjN/5kbmDZ1w==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
