apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgAMoMQYgwHqRDlqldqPhGxaEafy7OT7qvjlE8bHlu9M7od+67ghVdF9gnEReb4pDPGh7GV2jpTf/zrL+Y4KoUEXc7pKN6RB8l3vXvRiCreYohw7nvH4JsPlVL8nwHYwbfmdFDZ/Xbu2RnqUs6sCA4jZKre8ti4dzkBy3E0HkbPigz7RYPy0tpMcAq5xhky+Vx6F9B/+sz4JRHFfcOomA0vLp1krfcoS3i1fcTMLGUNPsdO71eearMct22N1h96d6bjS8w5qomPB/s3BpOzLEGhdl6K5GshHQxIbOvVSHqrpJKoVTNxX+nhv9xB0gqgPV3zYTyJsBdaVtZKtDy2Ud1P69+iBaPEtt7mmPaJRf38j+L6h/RPy9KjEetN3FFkTF2lGTfyZymbEnZS9woCGqCCjA1nPOt8JbmB7yA5g0oIn+tjhyb3EFTqxWR0j6kqt7lNnig08Au0+gibcVat88beOg+oRdVo+wudpuruE/cln8xsInH1dClWrkixe9m7/Ad57/w3MIskeu0Pg+1KXzUaD9+fAt7xTYkd43dr4lEO+d/uI9Oaeryeaq2tdlc+O4377+387Mfj2JtBHKz5FzQu3Ju5WvRQCA8p6+WaJHIkumqGjMslHjxW+eyKf8032n8y9vIQ2YLMKoxTL9Lt45Q/WJhw7hBJ2QAJTc3hUBwFQqALgKWj/Py5wyPFgAAeYhEmcLzl7ZS3A4hv7zGaTAi2DsIh2Mk9j8cfFvOSMjkJU1yD3vLSZvP6YFlUa7fsDOJQtyrq5aIHV59zIpKKy0hsT3yDxO5Nd8IOxNaYsrBijq21AR2LNnPD17lipUH6WW5vGAYYyS4Ae17JUq6hnvCpx2YTsvg+LNdkeWvRtJ/ySug0MRdjoU5sb3jrFR5HKCmIohstvCtt/NFmVaCjbR0jCiLT9FbHD/MLIaCf7bUBXLSxnFjKfnM2W5fAaEMaLDg==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
