apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgAi2DRj6xERchjlO140KklGZA4uc8/tLNcAhoNIMRJg+EUk0IhhEba8KfuRyxLiDTq0NqRUP3kgoewReu4/ITnYss9ogV1iUhKwtUxmLPZX2h2EpT7b3VgNfmg9N4gqhKowk0IViUgHt0xhAA5kF6SQlzQXgfZvxp7Swou/YuJbvzx2USBz2ZqcU/1S85hIJUfvzi017Pnu+I7SenMgCnWZd019balHp5XV6F/V7d4ozh4CHMW2XXtXHr3OmyLS541MITIY2jDWqiz8M8dbV4jdZPpQesAUFtUffR8vilEXSbE3wVSUYn9Z7zRNUEJnE5AujDDmcs8ipNP+pqr9nsaHUvw44HCgIfWtQnac3rEwtXP54zwmYzJiCgfCCamt5he2gPSWhj99FOqDZlsem+L+VupyCbrHFG9GPSd8nL3VI0F29uQ1V0myJ9kb/HCPh3Ir0G9nDISBBTkBdZWvyc3PosEpOJUVjah8XKeErM244s0R9tn2WwUEgS6z0dRlQpmsVn4jg6F0WeOOSsNQBWzI1rlHLhzbbMyUHC3rQyTeh9g0xhp9ySSX+56sdcD0vGUTiuuj8oksVrx2/rC8DPfExvBcTEpqrbVAFpMwD5CFtHFIsHZCl1dbb20hoUxaR0LX0Sdp5bpCUYXRi6PyuFlouwZFZtTmP8LQXtHrxrmLIQHbWclnYRIfKIlYqnb8UMelz9DdJoFmrFQk3UfzornjYuAYJURr1haFZ4Ff9xnWjgTn8XTFCVm8CjBzYxWYn7hrujfk+gUdlFMwaEurxNSww8w+MwDlafXURbYe/QDz/BehgqqVmwzam6V7/jVziYZDv4fSGVaC2ldjjRRvKqW598BCrStkUxv/pCxtlN4UfQCGoVwyt5KE8jjc6Ccz8V7FktIypgJeb3AWAoHBgcLVhC2iezdNNaKoh7bNFlaKX5FVIF5Esd+8Odw49ccydA==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
