apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgAaisCQNp+gDJT2hDA8aQJabR64FE5BAM4pySWftbnWGrhGbe22l8piIaMkEqu1HBUXGAP+OTnURdm6tlnrLomoBPgZfm7RnRXcPEippIG39JHPKHW0QDzx9MMqUKx7mSQ5P71Z4DF6t2ZQdeIS/EuU25YprJQNGai4YwhHxSUdTm+w1HfHYf2jadAy2/LkG1UueCHuJcUk35kpG38/XsGWJhrYNiYFaFbhE7TXph1r4Kwqz+BEtoID70X9iC82TxLKWz+QIC2liaSNRZzGYDVyqWIW6cHCHFFifgn3DhFe7fVBu3mhXvQG7Pbv/v2HK+ZDxHChJAnFJUg9qKf2h1A0CKonCFDq4ccjPpwN8071K3V1fCnJ2psmuocaM9+k9Ql9RQwsvqYT0ucBBmCFKQvTnofbruF9dJQuBNTC96/L1aheoSs+qhlwwwsGLSRldeq5AbidDHwlxf6Lj8G6awxTHuTVGQRXeqJBh1G958ZaF+6ZoM36oj1e4bI9w9Pn9GErWGKfU6l0JSjf1qHZQg0cbidzRio5aX3poc+ubVOX1I8s7ErKG2XrSvx3jHwiNzHg832avvFYDKkydx1NzLYRukrqdOZgD35BwOm6oFkJoTJqNqTw0uifB0Lz5Ix5DuP9+rRQWZk58EsbTkmGDWa9d0/XtdftvS9MXTfOQ2V+UXhUt3aowwJCRISY5G+kpZAC4FvnFP5f04jrBpg7y7cIaJYsLUCFAyw6cuwxecHOGSetj90L10Wby69SC5JaMhB3wVKrwu1/4elSdsmUuJtiDk5tpjp3T0FLFBFW8EKr5Jd7g0n/0nR4F9A6fb+9kCVS+RpeqtI2rX36tU8YCwnDrjDk6C8LKjPaL/oqMOvLK7Y/9SU8sIyaioDK6j13A2bQVIYpnAaWbfc8MnOFKb3d/JCWd8NLSk3rkozURZYZ7x31soJr9W4WNyP1kOCvkQ==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
