apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgApg5cZ+StjyuzMYPra/EHsSuIZdq7xKPEQfI9au2AijNB3AKU+F3bx3Q3Y5tQBmTk/NrHFk1bNTxGx88SvfOTnMLo+tKVs1aL++5eM0nTwer0+Lt9JtJtLWr1jCodz2ydBnwAiDF94aMgZPPzz2sFnOtf7cTxLgWQWcS1Og/X6BxROZ1QPvTuz07MoQGeOqhnG1syz/1Vd2svQxeB8oiwOInMguEgs4Iu3wbGYuE4I/r8s3Ap7mtomUugLNt8Iv06I+TsnrkEiMASE3ixFYqwStdFOi3uD67aykWaaIr3y4l9BNSQjnlvCk8zVWeofsoMGdiOeRscUYB80bKz7GsplWkssqg9BGEvHBE0WDCtq6JVGarNruDmRGmCKynGv9R6QY9qU11s/tJ3kwaSuKRWQyL+gm7HhIuuZSani/8RaCtxAZWdVFe71Qelu5uaAPe0+XC6+T0oRml/GKIeC3g2P1j1+zm6Sz3/u4IJKozUbSU8Z61eRS8XJNCRq+p1PUH+sVqRm8qP3vXl/UdLcbqOLPhfJuLd/hOOn2JawAC1ej7+FjMdE6Ri5SzUVZb0Zcx5Sn7nSw0M8NU9xozVuqSNCAmDgTlgNNh+CZUklajjg7ijNyxutvaul0tL533m6nFe0iqs7zRVe/6jQNSE/9Jx/mHdeoRYPIaSGJrrI8KN0EPF+1jnWvxyRn5iN/TrBwlbPgYtJR+GRMO+wj/IeLz8THBiPcWS6htN72Lnbm8Qr5DcA6EHnhWqZEWRzrE2h/owyJKXprfjofWG/EVWAsq+MXaDRhMQAtcONon2JM19WidE4+WOdAdC+XLkDQNaiOmvppy5+Zc4RPyo+90oXOTiZENt0bGXff66xNm5AidOE1KV1FHr/tOjZT8kTGI6YqGkFUFkgpl1Sh+iaOanurwj7ZY9bFVEZhOVlyqsEmTas98t/LI/nRzUw2W4RTysBAA==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
