apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgAsMVj52DpoSz2dWEfacaz+0pn759OSVml0uynj0YBg2zCbKtOYfDZsBraXI3M6pjIMi0D6NIDaCfeOgu79eQQdQoAqRv+df3QAgVtLXCzz0q/Q+/WXE2z7Vif2JmTf1HkHnJDFpRiF5z9LGs7lKsnl5nXrg/FXyQ3YBb+MmTeD3/F3kh4cz0qXKTbYwVL+T1Sh+vHcFidnssSEuh+igDFljvUEPU4fvnInCzt5B4djFL14Il0l9GHxpYZQlD52pmWBBTeAp5yrpkoDUJzWPtDrsWenrPkGW6mk894Psk+B4qRK8ZUewEmZpf3oty5AIRfUhS0fWYpRBMIw4uhhMJ+/thw78VgVV8WZgtgY85cs3v7EB92F6klhyycz8TEWA4dU5ANL/fgB12RYif18khoo497YbzIJyyrYCtEkeZyGFf/b4IrbNQsl0+Xgf62PVeaIIiJFExQHHotyV/7ztdGF6Z0N94YN/fUBjxKgOZ6dp6IdPVBLb5ZpbTuwV1+SkZNxaK2MbVWy7E+hvWXuYIG1httMkFNGEQtY/rCsKAXM3bgXOkJpxGCmwCYIxBZx0UjaTyr31A4nWVaPSebkx1fJKLCe8TnMVuYn4OKefiq5PVymyQqdWFK3UIb6EzSqU5WK1/FoACLYcvvQZR3y6ECy436C8ofME0z2H1PuWo/qxwvkmHbs8UT7HI4qCc61o4F1zWpXfxOAHIe+/20aw9rFs4YojRwh0cB4f4FrjVctlUjqLqs1OvT/z9527yjA9eV2TS4v9j+XkyMZLhQ5IOt7QLEKXjbSPJgT6K7f/cOhTkUWNlA8n+9j7cIzR1N55Dxu7LlXNxaStg88ebnzxCYYY5yB65UmF51uxXe4QtKSVqanKl+9UEm6iv2uHvt0cIUvIW4/yXdxaBDGQLMo+pRE17rQZB2tn+ARJONWc1etpCt279hsvFchaLYIGCINGA==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
