apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgAKtd/GtCd8zca3ErT6Nsu3sEQi7pXy0u6gZGDL97y1zdBot9gOhfd0UZa0DXxwP0uJ43MDmIkuwR6Zio7Aw/smAZOiAyN/BEKnIytckf4gaR+SCkl9xRpl3i160+2o3pE6Zx4DcDUfQSCIs3X6Ky3sQCqgxbNQfzpL1E36ZsBso/KCxPSyPU4L6pcFdh/bT5hGy3WttR/ahjlCRGxkkeVXD7FlgmhnGc1laWZMxJxz3jFQkXussW6z8L8ET0Rvhx9ga5RxpLGhzo3GqAftmyRHoafBOrJBrBtqFyz/zhdczfT2CfycCium57uOh2QJmmrNOVPorCHYEAdTD6G4tW+qNAJfn/MMZT9NEgD9+tbiqm0MySYx24jD/lhJdmoO8x3PQZokU49Hk1p5G+LYbD4mE8aRA5nk6kDQ+k+47+uwzCM+/GblDym3Qml56KJHY4g93XxCGmo/wnq8Dy3Ihtw3C81TutcZMt3wcfXdAjfUbOPmwTbTHozG5uQFLqAFeWtxwf+oz9czxQcpCsSIOdlVBnwZNy52HKCAGDgd6CZwPcQs4kHI6cuVJ41fNpV4j4hq4qsh6IexHvY+1/qOpWqZx9ibwibM/h40a+pQKL1e9PEwlzyP69qxYmyFgVSMC6DDea/FMzpW+o84108v9LSC2htAssptCOp0App/PqQ+FyV1l/Meqt9eGRbIXfRtd0SYxhFaazYQXve3ak9O16CK9FWTaUiiBLl7pmyqqyy1oDaiOoTP102nB0GBTN030GYLL91SdnzbiTPvT1loCUom3jFCZIQxm1IhJOWPkwj5fim1hL82qmsFk+gmdEs1NAhslMZLlgRiszJ5pscb/fXxINO1EFVXfL9RDxjUkrJk1sQxowgKQC8N2TtArHWytPR+tAX1ASulyz+qxLa7GKAXKyhFaGnZr4kEEqhzpdWFU95N8fuNg1FGt2ylI/R+IQ==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
