apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgC/zgYxz5JEBHX8D9EqPP7ee4A6K7gLejahLC9QQK5e7P9rkDgtTdaLvCxda6z6NI0lOCF7ccqf0LmSPaMN/XVNoQf6Qo1PdmqAQRR5Sy6a9AHRwn0RSz8DnDz0BDGM4ykavioR2lxktgYosMEWxSglnajFwLowmHw//GNq4mkSgMc4ETrWBzGXEoiViSSmqbnCCWagEFPtRTDYkNb60g1Gu8wSJ1eEzDgqbCyoQNZYv9m2vM5dKOJthU2TdQ74ah756FqV9ui8s5gDuWpNEVuXhr12L2VFpSSQ0wezU9Zdlnm0rwpFPCWrlJCgK0s3Guk6I53wfRmrCkqiqZrhvSBQQJAWuUrCidMfrIIa/2xeoxbHGIwcGAtB7QP1GNT93Q9rbyLcO0KudaaZeTqzMGqPCxMopO3aWPoNgnWtE6AFlhQb5JzMTAaF5QpBrR9w5hkybd3EasIxWZ4tXZtrr/tx4kFTLxuIsov88MGhhx4s3ClM2RdzZERuSccKpOpO60//EoHS4CIRsbY+5QB+Tq67J6KkerSl0TQTDRki+scwmn0o0wzXV0ui40ym974EFR7skhO08vx6dSGY1DANMpUC9hMOuEh0sw0tf4WtPe9hcdnHMdbWNcSO5vj6CCzT5a4WLZQJYuDdv1Au1Ql+D0p8xiSifEI2md9WRrEr9iywkVqZSef3qSlT1Xxw1zs1EKN6JZJduFs=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
