apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCP164GUv5XLLUD4PdVzSK+VxRrWbZjfLJ0exm3a6xgc3avREHbJVVCmfjmpe7I41B/utHc6WCJbnIAYLnzj25TFBzK8j328cyZ8PuF22yRfELwu3nLRvbrBtXuJXXcSDBTe1Qov0xJPwP38MOAF3tsSkqbEj4lTC2JHlxNsTLDczq2I+o2Su/5A2xTLLI1zOaKdStoVFAb6X4tDe/tJ8WR2uya+297h5aA+q5puOCzTxlu+1OUbt6c2gvrkNVNZJCzUa+qvxRGPY18keBlba4urJcUaSdQFj15KHeiNiqsxuBLy2C0+1ODmIWuFUpPp0Os+QiAlG9XvXxTW2bDfefE2QUkppnNGk7a+YRs/GitoG9laag9jzJIkGq1HCRE8LGT0NSkDAT0wtn1wH07Tgn2q1cmZlA5RAl2id38SGfrDTrb+PXHFN328UAEcKa5k164cvK6hduEkuynK5w7xeMp8lEGyqNgIo0k+XTyS5EOzC6U7wIkPkEHO31sp5FFe4TgQdLN53ES/iWBFSnhw6i4TyBJ7aaUcbMuUjjOSHnYTsV9AFy7IgLuGZ7Pj5a9ihVZmsR8Cpf+KNfHPMrZ9SI7Ci8v2AlEoNVepKokVXRVUr0/5C8FBV3xj5AffYhGIarKcNhnmNEKrWN6q6aWFpUYnoHnssFQw1jyYnEGEnWr4snNFCP1D6GlP46U3AWmFiVPmXSyJ8I=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
