apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCH3zNl7HDOUCl8dg8vBTexFj4uxsEsoGXkzaGnsA09Bl0IQWgJ3D4hwIHKd5/FcDj6MX6tT7Dgxc7Yre/X8Nb5vP8/Rs69a//7AaPL3XuMOhwxU/+GaoazulgfBxflrcUlv6/Up2KGJ80NuiGnlLsPu/Cssms5VBoRtL2tXR6RKMXwnTJFvyZaOMYGJpg/mUylQ0QJN6qDgDsgsJsMhmn0tNozBBUOcIzjLRLGusEuGS6ER+GtUvI5UR/CV18JdtwrEhVu2GTH/mS+raE1OupvXj+dZ7/wnjKnT3vHoOdj/x5SMT0b3v+QWDuQWDgnDCbQZBNj7f2mO0V1DFk3v1xuJF/D217NMUL4XNE/R1WWrp3D5s9nzccdekd5PuIESIXI8pv2wo/CZD7P25c3UQXTz4H9IVQIZ2HcZQjNRBinbbfkHK57OHKISTYLj3BzDLbd23+PM4FgIV1JsZyRVUvIndMId2z1EZITC4Z6kB0egAOFWlaAZPk27VN2Zis4FC16OnFIvUP0SMxdkh9mlH1oDa2gyR2kkJalrGw+b2j4XZJznFHvvJlA3/s3KGVRy9Mm9EPkBoLPMw5V9QgJmii9sBZ3RSLuuCzZKIUsOYIX8kF4thiMmnlcEzEWphs0KB9PehVviInLgUfHUWk9I2eU9G9/VzJ4owpU/VFtdwn0t2IunV16nEG3YUbtEURLhU8bvV5t9wQ=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
