apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBG1Hq55u1BTTq43kBATmx+9U3BFUSh6pSo8+R0X4wshcPiGexXgNUf7BOJavBLzqUhXouFFm70QYbUiADVTfLW/mQioD0Q2nu9Y6mbb6GX/tMftwyIzz0PQjo90NxvHbJaW2waUVHHVtAvhjNFZTEpVFOXhQ8ZY3VLP3x6XCJj8+GCY8gheYVrpNaGTTaRelkseFZNc5PY7oiGeBaKwdiLUWXIUlfOtcFs1ydvbdaF1EUSUsld9iQn4JBLNF2PKBpzBO/gjRO1JtAsD9Sn9JYKhx0itFGT0RsRkfKezHG/OVIw6p+hCGdmCId8pdDbXj7GB+9F62walfGNgMKTLZBNN5NqV/6NxoLeEUE0T68/CtQNLhHsbmAHwBSU720AbcH9S47GovtUINzPf2CiYtgsdK1/ZFsPAdTGBEkMwt5rhVfzoCMdno15w9ymoQ54eVRzvSy+Qd8WRWx/VBG7ncFqaQED2u4ucuNi4Dy/P3bnUCxplTkfc5AiTTpwN5ceI3EWP10jrVroS/lxd1bCIFMSWL9+TtN8kKujFn4NITFfJVUr5AqBSw4ca3zBP1cpzwVWBp9N5ij4kpr0TJyOt60V112ohhD7CzC4rkzmjM7vg8MClEbBGetHz1YnbBqL2z4V5pfZJykoPJ6Qgk2nX+eW5TdMmAZ60VbPpbNXzmPo8SaH7t68YRhE/AUm1Euk4kgB/fcWeOk=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
