apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCjlKWJWjWKv+GJ9UGh39b6Mep3c48fW1sfLFRZeWL6qYpSj4MeD/k1+D8VhXupxIH93/4JKY1bMo17wYTmAA4R7K7DUZKB/wTmbRoUusOc5/TSTn7fT8YZItWDAcjpfT6fzVmzUdMlp7Z1Q5Z03Ujhc1+Rdyg2z7xJ8nosEwEMv8HyTV8ts3cyC5s0QSJ/M7WXgI5FXMxw/VVXFJuOhCbB0MU/ae+/vwgH/hVyJqOA95juV0kGA9ERprlnttuQ/bypl0cJcFp8vFgri6yW+b+57fYRMUIAwLriGFSKcSxtnJlSxj1NE+RN7nlK4Q0WLkEVm/Mx2llc7bTCN+8b1K3VZWWA1xyqUjeZ6BSgfmlBPey6UooqbQisBtH61lJMcJtaRKvIfJIghjMFbWcsLGf/KJiyuV/zyiiSsg0elnjpfnqtu5brGX6bllmXda5t1vycy1uJ44LLrHzT2kvuvUX/fLkyaTEGaSTDfRGmYA/6hqeL0qmpT6YJq1feHPgwPTffdxubO7BMPLd4vfTzMhwKSxjyBT5Q4ykGIsVSCWO+M4f9teXP7AHMUUDLfLsyVUkFqCDQ/7IW7WscI3gqeUGZceqMBruacNhRzP7zzfsrxIzxiJHoPEXGMe5LjeT0eRF3FTqZn5/kerMvtzDCj/ynqzSWumoPoQ6RpLeGQ4AWgmufWrrKdcASdKTCAZDtE6FlMYV1DEM=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
