apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAFZDU/QwlRSzdftGjXVEIMtHoCQc4jlS7CY+94ttCXEQsjXEMQCd9J6aiAU+B+SqDLebAfcOi5EXsTQetrxD01ByAm2iiSj1OIuBdUchFNB97UUJYHSBVy+82Tz4CCNin9C+CM5ElBZSsE0uMsikDDqcZ3wNqDwE+BUqd3Z0DVAy9/Dpz+77O8i8KBuY8OK1GbEIL253bEwigelJOfgvicAAmRHPtCfHSJVDEijYjGsKmDNXYlnGDBvwvcOEeGfxnxDtlwtn4xVmF8A1A9SEOg4p0kYD8wgWAtYs5t+hinzPkwtpSYRvRFSNq2/lZsG9nAthVn0bATrD3+PSlUE13F0qGoPTvkf8KvLEcVeNaY4gw9gHXv3dYx+KGt9LO3sN+lLQ1p5zefBq2AgO+zBem7K5ixXpVVvdl3i/XEjraQG1rRfjhoj7RAwkl9bw9SNftCZWBSBmuC1vSF/vpxs0U+3jyTf0mAHShtUEPunNqm8SqT1IdpXG2KbqldgNeJGmKIyrLsFFSob4N7s9DZb7R1G8dsGmmkfER/xFKMIlIpFAyfD2jiWqzpUpNw/jmr2Ox4B+atPlujW5WGN21/2WJHub4uq52SrynlxlkASZx6LRfCAJvJhk2K62vQMGEWZncA5hzRXkwNVwgjhvDmxcClx6usnGWX6cQL1Xk3ha6BoFJINNhUURtOBv61WCT3cpkHf+x38rM=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
