apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgB7OGxkmRKehAMZx3jUnvxzT/Cle8INDr2CZ/BK9hFOSyUaHbmAgVopwV3jUng9z1hFAJ5h3QueCaHYD12X1fp77Jj/sGFrOv6Pewkx7EABJCTu0vlp6M4To34Nv7o4zYf4dYdXcEIB897vFMB3xGwnFmY3zIOag6E/7h2IUBnhFCCbFfKzQ1m1tqYAMdhV2ev44b+GZ4jTharYvJybdJ/NR6rZYcC0BKFT7ER4XL7l9HEsLT9P66pYivIKBHkCS9bHlOCW3p2jnmHAEU9nvRzmCWQ2hr3GFrQLhSBTwANT6Ym1DzChf8y5zNM7AK/+abJ4VaJCS89EALm7WfN0iyf/vVz+xOtoAmahT6NFHiR/c0lndLEVpKfXhrhldzEACUS5cAgtLtjVQF2M591l2zGaQe2PY99Z9vxQiafaeKvkZkNF1XVvY8szS+c7+LZ0qGroOsn4kz7wiQaKH87kTsuonTzdHs3MHnG6Jllni3ELKv802WNiTvK4o1JmUhvy9aIqFBTmHW58xPknKHyoYzdIwcNhijylzN4F1jhbGsMGFyv9M92fCoZMT0gKNY5mVqTZg5tnDSm7biww4uwWVkmJB8HOSjlAF3yyVxOYoOOpThrclVJVaw0sJKlV/rHdl79NTRrA5u5vc7EZ445uOQr7Wd5q4N0btfbLi9l3l6Uhp1VmcRgNYYgMozpZrsOi/1fbL0kK0zo=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
