apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi-svc
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAk0Cb0tpFsSKRlG6Hlhf6/5ANgWgf88hBNoXa3yYOzvKCDNaoJ1dwlMLV7TeXTD+YL/lGg9NXxaD5QaDUS/EG1Ng6fkvqu7TKjiSlEwYOSDZ7/TUwFDdsSF9gpCdAEP3T4gq4c1XLVajgfb/xTPX+8aRY/mV184t/CckUdOOKwc0NnoYRqiT9qHGcCpNJrQ6j2zvRasKEDRZntEALFBmCkOnH/MQSjCjE12X/Iv3qtLc3uh4DIT2rnN21ETyPoO+amzxr4PNVaGdTfdjbynGRJfh82OUCn6vRYeDOEdHxih/BX7Rzgy4dVAGrJaZBLBUBw06IwBTWIlOXFVJ18mkFpsLp3QkLGn2Bq+YxBunVXNrY12hz3cojNksiVlYBfxJFHyPHCWAb3swyj57OZTgZfPCJF+rhOLKSypZqpHNBflwBZeWH40T3RY93u8u2BXY8Ed6tfss/ZzuoUBo0lXTwtZKanpnl9gf2vaxCrJChzmTzINcpsPcj9kUjIX1c3v3UFA003Eunr7bL/ja7o+ISJUguqlxOj4KI7Ya7Wp4QW7VUXIFa4bnUYlX7B1Vps+89gl4PNluGA4s/ZkUk89v9N3loqJESwU+e4MtQ0CwhidejDC9cObrWzk3pY7uy+g6r7tejk7KHFmRaVnDvncuR/B6ifg6+00wI6VNLTrk+O8tFxopOe5Nubarr1NiU+EWoTeKkDHTo=
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi-svc
      namespace: cicd
    type: Opaque
status: {}
