apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi-svc
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgB59dPm+Neg3cvTLUKnNetgSl8P+8F28s30OCjDnwwurZy2+XwyvBNwFwGJfvn/86wx2NMhNnu6s/BnknIqpMx5zhD/FD65WNP1VyTh1ecbu1ppjHLvtT18G0C8vl1FKFIRfFzag/GRaGOzDXseH5PDl8iLgFLozSChR+J4MX2ZSK7jFVvHRZVovGqRQNQ7q532+UdSFJoM4GyTus/29tA4mtBND6Q5o4ztxRYRhhdaHeVOBmm4QOAjixK/yfjUsug0DUWkJJ8gQ66CyzbUWERmK86ELeH9j/fiNJON+7uuSR0b7pfPiathuCpPMjBeSeG8PO4cMotcXhbkFBFZf0V4Wr9bAdAUharpN+Le3Ua7BEs7XPJ6HleScyPQZr8iGp424IEMkup9LgYRGzrSU9uD+Wqx3bRuDGlaT9JtA6wNc2zmW4583BEJnxpb5mjGvCPnbvY70uin9GGQqq2abwFefWz1tiKoZ7ERiwfAsLNkUpA7O5UP3BpmoyHAEDVmGQCBraUy5v9VH+Esb2VZHI40blO8eFuEFpJLLgQ76gz4Xy8iAWvz2T5S2TbrLQ9+LC2iaavlw5q6fKXsYmioO/nr/HIDDskyyEw29Mj4/sM0afGJ7JvE++ac0+DPbi+OgR6/gwzExcHQwrLaEqRG4W8lu7S+l9ytDrj7t6aDaGC/ex0n4JGn1pn3KpytGqXj1qpV4kEcYP0=
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi-svc
      namespace: cicd
    type: Opaque
status: {}
