apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: stage-bus
  namespace: argocd
spec:
  destination:
    namespace: stage
    server: https://kubernetes.default.svc
  project: default
  source:
    path: environments/stage/apps/bus/base
    repoURL: https://github.com/DhanashriPalodkar/gitops.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
