apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgAE7aCu5ZCZTdinbENOoDcOetUtNzr3E/mubBSHxMe2vHg/D6bNW2PROgSiEQ1euR07D3/kOb+66n+R+qlQ+d99EPONlB7vSyd4G/fVFCNCrfrIBoEwZ5HybveWFPIFDeoip4oXhdAX3xx5VhWYdofPLFy5bmBLvv9PwBoLuPfXJP3wEskIR40U7eISFWu1sav06qbFj9FrdqPxp4hy1MrO7WEcxYjgYz+rSf9iWUA9mQnfCN8K9NWJYoTe4CJNpdGhmLEh07iw0jVXob6m5ccfmzfCyZyR6+0g7MPTIxYkbQdSi2w+aAPGF69ZBoGKtY1DCLAVIGuhYq2TBQ3iWJ/elkJTnRFHWt22vyQ/sBS5Oj4CRUsfW69KwWlwPRChfGYyPJL2ZyQjlHHE5sMU2qm+W4o4h26lzFQzXKaYSrooK2ycoUrrEFI2hyNRfjyfvw+EfKtZoX+INTy67K5tv135i9cNb/L2Vv7V0gTaL1HowD+SmPOJko4hp4V31nN6mGDxUe8r1U21eWEnT/uJq7Lzwa3+v0Ogd+O/+8QjtrOEPMbbJ4xlAizKwvmgfAXwydZ23d7QQzsD92dF5IA9KWBfPcdixFEv938e2aJzBNGHbtDtLQznwmhxZlu4t7aJxXkPJ8dX0T2gIqwl4JW4uPD8H4v4IMbyQapDzNfU1chYC7NdTtMDEzmauaNJ4Z+RmIRekj9Lj2AHJuYVUWx6rarTqzmPT5muxwl/Mm4DJHPSZowDfucwXOzrJOkYyigZAQBEJunwo1oFla0hYR2TLiGvwSPrEfxuG7TYIpaESmGoBXEbjRdenPlWo79BBApbmeM15uD+A8WwLAme75EFRcS81MJQUtZ3Oo8f9CkaHTzbqOq6Zey37IJI3V9iPaITGouOU4UcYDpDr8r+TFSAKhLwqgXAsAOd57iyWqyMvMpegIFvxQHIsPSJ4hRtt2HGFg==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
