apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgCyx8lmeVp0gksgBBu/ZyLso0Lh3lDca7TBVko1/ulffssSkaQq6MoImE5UsXpQz9yFa2lX2s+5q7g95J3s7dZgEhP9Le6nFJfLlh2vvwGBwKmq0i9fCGT453prBhJX11q5dhuZu8GpSSwgFYFp1Od92rJj5P5pqRcwwHlQVBEwnyG6m9gqADP4Kfb/mGH/I9FxELri9MGsJ80rNbTqaDIkGkwzBJNMSGDZBvejbYqNY17VAN3LT+tlWePgHIfaQTjfQXPwWiciFsN02ZQHjuwvHKwxQmyEnpRAGXEwntOTLaPPXq+hGaT51OCftd6s0TtYswNeCi7gil7SGnY61O8dSJD0TOuhnHzhbpWlqGnkpO4obZCfz4+H2HPlulVZyrvw0ZsOnIF++2tUCKyAYIyajDhFKTr5UHuVHP/0mHyqdC/Q9UwElvWAyAGcaHxdfJKuDlGp56AVGyqJbm3f4JSIXJC6mVELBl9HUihv1eT57vmquIfPHuNKb0T8rPxMFGPUqJdL89B7wSVeRC9wu221RSMTwasjFQF6hehXddtGbqi4/2eVFP0rVC6KklvlLRfkhoHKOOjPDQKJbCi/OMGd5OKO9l9xypDSj60H8u6+Ton+x22BspRLiLcecxJUvcINOV9SQBAXT2jdDjqCWi9+SB+tZLAq1ucI1MyhgQ+aieFtN4ZRW9c9uFx5UzjtUVpK8cykyvRqWQvcXvJJm8J2zo9ytywMNUu3bUj2tHwZUm/Wbdy1jqrlRj+eKL3KseW1R4Puk/DJ8+f6gj+KRASlClz71mo1Ag2yYNY8gF/etbUa2dFgEzzq6f3DJxprqQ/Mb3M4nraCa7Yv4+X9KSGqgq4JF4ClLAEjBm92pBC5u3hU7rLfWS/Gje6808bInrQI51yPJvKfVR+vZX1osjpBi7ssQBYRCd95L1QRTJEQHQSGINQy/zHNVX93HsG5uw==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
