apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgBJG2TNf19fvQ8MdLyJrhuimskk1CgF121a+mlaFtZZ2ZaGUTuBI4Lyq+pOx4SO5XP1wGGOEaW3m6BryNJrjPcVRY7wprv2WJAd7zhT/A1zFnzf2I8yXLSh3mgSU4XHlcJbiN1xwT1/HjlzhAl5mDwoWdKE5rRb3PVQrsFR0CzpLGaCBdwdzaJazKZ5NFHKTonWoR38kT/Uyx1F28C18lYodESjDGh4MFtA/Ga/et3K7nmOYYPQb2LbIMW8+zZY8EJeio9VoWPvpLusAgiWOELG2wlQOfpVrpUqxahUV2iqPjRPWpClK05yo3PKKhIfZobYDzu8s91EBU+ApJphk/kgsiDrjbTafnPCOLkpFqijXHcdmJrxmkdZKj1BwoHs2TGLb49vqiClwZ+ymnioS997uMrKXpfcsjU1Z1GG06ZSs+EP6gXFPUqbyiEtyQbtA9FZGnvuBLb5pOM8N1LBkXquep3KpG6nQAuGDS/UEoBDH9yeFXrp8nstG8Zrba+eFOpIgsxdmx2DmISwd5gpJFD4JZyYYsE8xX+UJrp39tSBPD8CDyos69uyZgkSELANRhTiZizAzfcBfbXMYGLoxqdsP79+9IgONTpfyIjXouRC9awhs+nnDyXO1yDBqd3aZq+q2I1AJLerfV21KrqNzZf+FWHkXsGgTwrHQql3b9Pi17cY1NJUvp01gGXlxfrASWPr9r7Y8Pd69tIGEWNV8HPl2OvlQr8ugUKQ+6qLtvhRkS/NH5zQd3X6zLkg373WQaD1Zg9kgs8mi5CjNvvIX9iqdI293YvuQHUXSLzQxBSWXbuDYhvkmiaKlxn5FnCWl3A556tivvlGfZxw546D4kTPst8cTbZ8CMrsBABkuEwuatfjX84ZJnxIVZFUL6UBLVkYDECMPUkNaVjYrTnQbIEhS31Wg+uqgDL4SToIpYD8YCzV0V8s/sfG/GHothruHQ==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
