apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgCp+FGHoIoDa4T6sZot2aBrfcY8ikUTPFZxN8umrrrwGMslPrL/+viwFx1u2Ap9WYoxjKVbrGb/0HK4DXpBDMx2oyx+qHtQBGRJtb4mbR1CpXxWO7/dGn0vPQAw2tn8eU3ULBU8S8C/VWCq1Hg8E3kWworim1rvstsyGt2Zyr5djXaOJ0mGpkLVLGBIZwXrZACZZ39hJer7dFiJIOJwJJfUR+kf6L25+WymvrZg7RDXzLAq77EY7c3wgGQjl8+3gZIfbc4zfh89p12TdkGibWBz23UrwiQpndtirjvXUSGrE3QErmw21qCPz/m9YQJhuR8OOJ2MgitNC4fHYDVicBPnRi9OrW1YA9ul+BGi6oTxxDEBGgk8dHdG8r0qxkx4ofy0NLswSK7SQlvMFt54b/Cyuteeeu60b/mMSuHydCLh43ekqM0VuDlGZQbyxTZcYR8dlkQakMgOzeLs831dk+alMGzCDFGEyGF3p3m6fpHOFOEEdej/YhZBLsbW4Q1Z+RIYr+LjoWwcl6VhmPIrcumc1sZd+JJ46VgOSsFkv/J5LDSwPmphz+M34QwrqelSnE+uUuFXfLUz0hTc/9VfdXRtyqIcNnRfvyYCxs6vlTHbP/118WJFjQcT7jws4zlAzfBUpvzzyUCapzA/KPSy5BHDtijuIC2XAnygko13JhhRWYwKClAtZWUq9iASMgodXZZMzHDlrKzYx3r9cDIHM/62Iii4cYmW5sv9JVB+Y+LsXiUb7C/5T4WmG1Jqhpf2MG7iti8a4eOX94yNFKiMnMRxL+E0qXy4QvjcdcihaTYcb6Yk+2K/RY6+p0yyZCryzPSemei92zk7HhKArBjn0KOB/7stNa3/j3D1h7MHvEKw4RYqVmGXTuHgkIKK7cXW1q+YLIhUvZNnNLwqYUe5DsWwpP+jgWDZA3ryVQ8nZmpj24wjm7h4XpDxhTOOmQf8PA==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
