apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgAWmsFim6Xb7Rzivpzkgu65EQM57jH9ucPo18ZxD7JgNgr/n3dJ3pu0CaciYsR8HPd/xE9dor206fx5xGoNwiC7nJkDT/Ikqg59C8hdJ9aY8203YTfpX7niuAt+4QnGPyHECVtFyOYRxaDZPK1vhl7yZkmV8uIIlVZN/2i+7C4jqI+EeLix8dAx6ySz1NW9XLcm+30Ij4IJh1k2KY5vT15UDRnV/bgGtQnTHYDzoq9np2YV1XfRsJFRPzVBkNne1bHZSwZVaDimTAe23jfXuKFyi7Dc7petVDgKFJZtbS6lTwELr1hJdV295Vk/wjnhbmvMgJr7X5X9y+rAKXifMte+m3Uoqb6ZZO/BWHJCITcKyJxC4lAY3oUzg/ztyJZksqRCc1Zl0WoPesTast2rg6KV5o60bUJD8S7WFjAi/pf3LemB4/VMuvxMvxAx8sYzRkpI5r4t+yjLW7Y8ozKqITV6E1tZWljRaSNw9Txyp8J9Mdmo8h3YTCZ2/Vlug/KpTK2RyNtJ3FyXK15eJoiJTYrS8Ry2UEcHtmgfBLz9qEB5HdxnM799sig+WUWCrHPFAfILUuDtTG1o1Mj7KbZ+dcW6GhCJU9b+MezaIwYMFSt0uczcc/r8PO5H8O8Uk4BpTpWoEeQvDtD2hfKG35ch8lD0jD/SGQvoLnm2rrs1SN8K/C+IdJIyrBT5GP6l3xKRjQ4NGg3A7UQpvtaNh6vFT714+3hny8nQ1X8D1B6ZT04CPzg+TzqiQH6AcZQjQPdNLLcYBOU3Om6nbID1PGil2L3OzgOr2Tk48tscHQlN9gBYwcAW1K4g9hkaOnVJEk6qwfpjyRXHMfeG6uV2djm5qfBWRex+h9g10E+h1NtKOJrgG1ugrHm5ur0LNouoV3CCaBxtKlWZ+yhIRYnBeOgBFLiWuTKab2Mwf5hBqM8xYQ3QU0/0s5ObhBKWalr4Kmi2SA==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
