apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-webhook-secret-taxi-svc
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAftvTXj82QruI0Qys4eGzIZFqLEXiAIIgCcLSD+sGtbd//D3rT2+QXUcye6Zz+pnuJrKzRJfRwgjKyXzJPjXK82q4hTrYeD4WZ54Dg6LSXgZoDuPBM4pY9n/uC/embWvFu+kuRKu5pyw8EZsOQqs3XBndaUVTzQyQ5Nf4/OXBahJq4Pondop4hGtA9OpTPGY9P0r7Ka86DT1yowPQAu5Rjf0HiklOOS9csB5K1CWjZ9l7s4oPmSCo1D6MhjY7J9nXX9Bpjcvf9i358it8dsOYGPW1cc9JrKyzIZM2D1MCWHGPa5Y1U2NpnHxjET7rV7SVNbnLOD0kdlgic5pk8KmBt1ZgoNIpEMp+tExAWfh6a4Jki/baRC7K7q63OBdINclkucOExaXpXAOQ9CgmqC6PZW4vcmhs3nBMEkTw0IwCRL+4mE/+5Gnyz1Nr6LZMTeYjD/7/XAxWZ8AAUhotI69psOJ6gIqOGM61ncdSo6/vP6g2Onc0EGXt/upg6vIJ9zgzzu7gCSJ2KMyeqwrk+nOm6Cs3GWwQ8sLy0O5CuvBD0nnrKrJfnDq7mn+cPwhhylnbU7KyPYPO31jRoCeyo/6JY9W3iWVNK9ag+IHdZxNaD8HFY5Eu/+B0u9XCdAlN33DVFb1t5TSs6r9zuFJdtdsOpNiwh+xNTqMgqgY5fnaYpm0npZqRewfxtBSBI2UEnVdqhF6V1/xs=
  template:
    metadata:
      creationTimestamp: null
      name: github-webhook-secret-taxi-svc
      namespace: cicd
    type: Opaque
status: {}
