apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBSCYHF8I3s/YG7jTNSpTDt/RCg1Tr2D3mGdQsuhLRA/jAU7jZmmdrtni9+zVPiXuIxzxLk8CxKuYF+qxDJumhIrsDZ19xUq0/dEODVp4RW44hInRmRnB3m7ZGrbADnOkDuMGnBttILnBM2eXavzkcla4f9up+ugrXup+dZXmvpOK6KMb0gywjy1Xa+uu6oTmPK7b8/T0G6j4GpaAWG3krB58W0YhPFFff/ON3IiMZw6JfE9goXxxzPvmb4M/NmYlECWHuAbBiJlativ+ARvTIyLcTcWtZNsmtNMyhiZ0Rtwa0nsczfVDOhClCTR49xthg39clJp57xnOksIfiqFt1KK2cSOif0TY6jPHX2kXHo/uK1PDP7OxStf+KqLnisqH+8an6oYb9F8ze+ioa0jQeNjfAZ+6bdxQjkyAf2ukDleWA9nxhVuCsKTJjpTwEydyPXTgPhPDfvpk9GP15rYH0ts8CjZ02hpyWbc/LMmOzWF1Re5+npJpta7a/OIzGRaR+KKqcSufWtgpjXvPbi/pwwXzHur4bKpGL93+KVsvvNHAZgFz/24bj8zXKBISuc/E6/3zeJuzugkeIRe7k1qjB29Y+bDaJmpKycp2cG9rcwG8rYkKkt+EDHgs789GxskX3gNNNbGjw8P/jBIKDkM/PBBmVlVhMPt6kqEtSzAUEtPaDV9ssLNJPXW7VI9lppVrsiTe5FMHI=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
