apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgB4rW64ZaMvs4fKs57Vnp3m5BuonxLrqsN1j5m53x+0i3oQxaDdFF/MtTD5yOFRBt6B+L0wel/W9DFajyJkRKJL4RPixIxoZXgOeybIkzMGGgDDrmj3ERRVorThRxJA+dgmbRD0J8RlBVsvAEKzxGFXWqKq5eScePHfxsmJY/s68punVAhx/WhZ7Qgzq6PDF16qhnIHwcpo9IFeuw08T34IxmET/1pd6PmiTPR56+0Jld0Cl4LEZ5bRh5GYtFjR/X/+NR2PXZvdWLY13kPHjzKHx1bR54BenlxAKaAFWmfcK+6c60Yl+NfFbmmCMlMwA1ISnBc8HufnGnSHGl3CO/etSTYCN7h59IIrLVWYb8w3sHGEL+NSf7bV++Y3fMt8KoZpAYcfQHR6UBdnwRR9jOYhe1REMtu+qIkZMFL9YN7PVnkvrnaemNnm7VmbNdCi1CyFjaNUgUnxDTGVr4UuAKOnKnEf64fGcbHjVGzgykQ5ITyzfCrO9BXyMVP8yLccQqj/29YlKJXKMi/kEXHRVUvsrAiLqR25603x7RRLDTsgfopuetS263/wIHfygI8hqHdaYwg73vRIw/YD9Xzp+yByzPZ0yWQa8qN7S/bVOTd2g6txKLvpfuGfzuvo9pJ1Fue1dS/EadIuciDPL7sIJ+G0i8fkE4a00qfBDyN3qWiYdIa1Ytiqk6qX4Zx6thJk7bgKt8Z0Nrg=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
