apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgATm/BhEdSdHnqiUWo5lswsBQMLEgt1ZIcEl/7AtLAcD+skltHRvUL4p4zIwW26wbJGbl35B21FmqUYFUV8fR7dRWFgHiJugaFzv/wwCU1wR/SyJLVAYBfttN34psD5Q5IqQIrJA4WFZA4zfXisYd/UYRmw05zFbkhJmzvUug6ZVCPdEgJdXb8hGrNHxc14VxL9AEx3FRU/QH7hoNSxgIgrd87SRdCzmitc2u4iUv4Tkp2ocPQZWdNh0u4WTO0nWn0HurwGAwSEcsg2lcvSv8waUsUVR8QpEKVkgItev4OWgIWrAujf7LFg3PWARJWZhfSJqklVkJI7dF73JjcVjYY6XjoTN7YKMpJkB9Ps77zxC2iAQ9XbsOYZ0TyXE//25/kLu6Zpsp2xGkaVWV6b2uHXvUMW7/kd/WvsbaDoXrYkJobuavCYkpqR6bitXxKfMrdge0d0lSpvW/fUVoRJtlLtSh+cn8JRV7IuS5ss+lNLMs1Ko+S/YzpDrdksWRyhZj30FxZ5zMS4xkkQk5Cf0Zxe+FXSo0kLC871LyYbdvF+0c+839+ksQpsD9SruOkDIwc+YnLpYl/88J1Zh+wH9qnVKEc0vywVyXRh4g4HnolN2yyT0WJZ7lQmMiZTgkNqMi9hflM2TFrBalK4hn7Hnrpe2VIJlkbwtdsiVHFyiT/1yO/39EDtnvFc0H5Bv4n8ertIL9fWs1Q=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
