apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAAy/62b8Mxywr1/C0BmqnDVSjkQGZiIeG28dc1NORWXqLUlx4gNPtUNWWu26rkGpNkVIEIgjIWRqWox75IWGl4HyRoQ0IiAeX7CpHUHGLpKn0io2MRxNH7H/XPu//Qb0pFXHuxjdvj7RFKHSDrXZQzGMWx0oN/m2E8ntiNwVY2iED4ZZYMJW67dv1OdTPxI2lk7ZqERCLI+25Lf7O4PYxrwQkcjG9wJJmDqd1d7G2QvoXw6gVLf2xkJBR/kQFk4cCpPU/3ObR7l2Ctfkva3ng+d0g80Whn8jLmbmh5XBBPb8TuCYUD1MWSNX1RXiTGemV+haB1LsQhCeMb+0dq+7YfyBZzGNBECD+NeO+2mFFdc+g8wqVtQM6Xy/4+9PTNZOrQjNCnzIp+slxeUpegNeIIvKdEfJcuLC5vGcQhClmObyOz/zG5wegotyYn5y0osSA7sCz5PHWmNMMNavIW4hctVzUoZNdmfBP3dNzY/L5r5OgqqR0slKMGikyCeFWEiaXQxXo381S/tluGON5+lYwAujC6I+DZeHaqMScktWtGKwYBu9K+p3Z0fZYpjlTPWvrFVmuv+p/KxLALNyMuHCdgsz4FkTbJ31EmSIRgIuNJ/WJVSLRh8YEs4mzhwWkuUoUbaOltQwOJJBCXebj7J9F5j2Quk6WOxTUpHhtPGZwCx9Dce0lDxOn5gRu1uROsRDHcJ+DERnQ=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
