apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgDM12Pv9Rqg9Dhqw0ifa2fAl90Jdoy1AVlGbNyEE54wljY3ueQ1nAWm6g/ckiuVVTgDTnEU5Sd4LhAPXjOmLHPMOnIwQ1+fMadXiueAVJv01hkpxCidJhgYUDFqw18dTlScC0/Gh3ufN3MlKC1ySuaRFyPxsuJkjAlZ+AOxkhI1VDTicEPpGrkaCNufZAOYroejuDKta6hU3+Etu0maWBglJMoSZnWQIyHID0t7/3uMiDK1G8DyVLoxTkDPfOGz+iS880DIuU38JVjKWcEBgxqt97g+lv5gCTtoY+i4ssr/EQO0P8o5Ezr3OWVgWijQZHaICjVTU1h+Grs3VKLDQk8VNAFurm2U/s7p2FY0UgLohSg8+VCveiv7XrIylZ1SoimBba1m8Th6/faParj3ctjUk3vWh9nNXbrvijs17GA+AUDr0rPBJCBBHzZo6xexA+qaS4UAeSSoGrhK7RCGdG4ljoc4mthU8OIj59HLOE3NarQeE2P096Tcvor+OtVq33D94hHKEFV2ix8KWxSpM5OQXX9XfHY1fslVt0ii4YbMossevM/BWuXpmnm9K4EoBnHCDOhitqEjHMvTEsI2hsUXj9NI4S+hMH/mwe+VhH9Izi9isaoKA+Puay4gpnd4YXNk10WWvxS5rQLsVryYQFdY/bwjQPmf4U4RUBR8Iqs8UjcFI9o2X+ki4QpWcEu4o1yKBzeltiY=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
